#!/usr/bin/env python
# -*- coding: UTF-8 -*-

'''
@Project: NarratoAI
@File   : subtitle_optimizer
@Author : PS AI Recap
@Date   : 2026/09/19
'''

"""
Subtitle Optimizer — cleans up SRT files generated by ASR engines.

Fixes common ASR issues:
  - Overlapping subtitles (FunASR timing bug)
  - Too-short display durations
  - Zero-gap between subtitles
  - Overly long lines that need splitting
  - Out-of-order timestamps

Used by generate_video.py when ai_auto_subtitle is enabled.
"""

import os
import re
from typing import List, Tuple, Optional
from loguru import logger


MIN_DURATION = 0.5     # Minimum seconds a subtitle should display
MIN_GAP = 0.04         # Minimum seconds gap between subtitles
MAX_LINE_LENGTH = 42   # Maximum characters per line (auto-split)
MAX_LINES = 2          # Maximum lines per subtitle block


def _srt_timestamp_to_seconds(timestamp: str) -> float:
    """Convert SRT timestamp (00:00:00,000) to seconds."""
    match = re.match(
        r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})",
        timestamp.strip(),
    )
    if not match:
        raise ValueError(f"Invalid SRT timestamp: {timestamp}")
    h, m, s, ms = (int(x) for x in match.groups())
    return h * 3600 + m * 60 + s + ms / 1000.0


def _seconds_to_srt_timestamp(seconds: float) -> str:
    """Convert seconds to SRT timestamp (00:00:00,000)."""
    if seconds < 0:
        seconds = 0
    ms = int(round((seconds % 1) * 1000))
    total = int(seconds)
    h = total // 3600
    m = (total % 3600) // 60
    s = total % 60
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def parse_srt(content: str) -> List[Tuple[float, float, str]]:
    """Parse SRT content into list of (start, end, text) tuples."""
    if not content or not content.strip():
        return []

    subtitles = []
    # Split into blocks by blank lines
    blocks = re.split(r"\n\s*\n", content.strip())
    time_pattern = re.compile(
        r"(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})"
    )

    for block in blocks:
        lines = [line.rstrip() for line in block.splitlines()]
        # Remove empty lines
        lines = [line for line in lines if line.strip()]
        if not lines:
            continue

        # Find timestamp line
        time_index = None
        for i, line in enumerate(lines):
            if time_pattern.search(line):
                time_index = i
                break

        if time_index is None:
            continue

        match = time_pattern.search(lines[time_index])
        if not match:
            continue

        try:
            start = _srt_timestamp_to_seconds(match.group(1))
            end = _srt_timestamp_to_seconds(match.group(2))
        except ValueError:
            continue

        # Text is everything after timestamp line
        text = "\n".join(lines[time_index + 1:]).strip()
        if not text:
            continue

        subtitles.append((start, end, text))

    return subtitles


def _split_long_text(text: str, max_len: int = MAX_LINE_LENGTH) -> List[str]:
    """Split a long line into chunks that fit max_len.

    Tries to break at spaces first, then falls back to character splits.
    """
    text = text.strip()
    if len(text) <= max_len:
        return [text]

    chunks = []
    words = text.split()
    current = ""

    for word in words:
        if not current:
            current = word
        elif len(current) + 1 + len(word) <= max_len:
            current += " " + word
        else:
            chunks.append(current)
            current = word

    if current:
        chunks.append(current)

    # Fallback: split chunks that are still too long (CJK without spaces)
    final_chunks = []
    for chunk in chunks:
        if len(chunk) <= max_len:
            final_chunks.append(chunk)
        else:
            # Character-level split
            for i in range(0, len(chunk), max_len):
                final_chunks.append(chunk[i:i + max_len])

    return final_chunks


def _merge_text_lines(text: str, max_chars: int = MAX_LINE_LENGTH) -> str:
    """Re-flow subtitle text into max 2 lines of max_chars each."""
    text = text.replace("\r\n", "\n").strip()
    # Collapse internal newlines into spaces first
    single = " ".join(text.split())
    if not single:
        return ""

    if len(single) <= max_chars:
        return single

    # Split into 2 balanced lines
    words = single.split()
    if len(words) == 1:
        return single

    half = len(single) // 2
    line1 = ""
    line2 = ""
    for word in words:
        if not line2 and len(line1) + len(word) + 1 <= half + 5:
            line1 = (line1 + " " + word).strip()
        else:
            line2 = (line2 + " " + word).strip()

    if not line2:
        return line1
    return f"{line1}\n{line2}"


def optimize_subtitles(
    subtitles: List[Tuple[float, float, str]],
    min_duration: float = MIN_DURATION,
    min_gap: float = MIN_GAP,
    max_line_length: int = MAX_LINE_LENGTH,
    split_long_blocks: bool = True,
) -> List[Tuple[float, float, str]]:
    """Optimize subtitle timings and text.

    Steps:
      1. Sort by start time
      2. Remove overlaps (clamp end time to next start - min_gap)
      3. Enforce minimum duration
      4. Split long text into multiple blocks
      5. Re-flow text into balanced lines
    """
    if not subtitles:
        return []

    # Step 1: Sort by start time
    subtitles = sorted(subtitles, key=lambda x: x[0])

    # Step 2: Remove overlaps
    cleaned = []
    for i, (start, end, text) in enumerate(subtitles):
        if end <= start:
            end = start + min_duration

        # Clamp end to next start - min_gap
        if i + 1 < len(subtitles):
            next_start = subtitles[i + 1][0]
            if end > next_start - min_gap:
                end = max(start + 0.1, next_start - min_gap)

        cleaned.append((start, end, text))

    # Step 3: Enforce minimum duration (only if there's room)
    fixed = []
    for i, (start, end, text) in enumerate(cleaned):
        dur = end - start
        if dur < min_duration:
            # Try to extend end
            new_end = start + min_duration
            if i + 1 < len(cleaned):
                next_start = cleaned[i + 1][0]
                new_end = min(new_end, next_start - min_gap)
            end = max(start + 0.1, new_end)
        fixed.append((start, end, text))

    # Step 4: Split long blocks
    if split_long_blocks:
        split_result = []
        for start, end, text in fixed:
            chunks = _split_long_text(text, max_line_length)
            if len(chunks) <= 1:
                # No split needed
                balanced = _merge_text_lines(text, max_line_length)
                split_result.append((start, end, balanced))
            else:
                # Split duration proportionally by text length
                total_chars = sum(len(c) for c in chunks)
                if total_chars == 0:
                    split_result.append((start, end, text))
                    continue

                total_dur = end - start
                cursor = start
                for chunk in chunks:
                    ratio = len(chunk) / total_chars
                    chunk_dur = total_dur * ratio
                    chunk_start = cursor
                    chunk_end = min(end, chunk_start + chunk_dur)
                    if chunk_end - chunk_start >= 0.15:
                        balanced = _merge_text_lines(chunk, max_line_length)
                        split_result.append((chunk_start, chunk_end, balanced))
                    cursor = chunk_end

        fixed = split_result

    # Step 5: Final cleanup — sort again
    fixed = sorted(fixed, key=lambda x: x[0])

    logger.info(
        f"Subtitle Optimizer: {len(subtitles)} → {len(fixed)} blocks "
        f"(min_dur={min_duration}s, gap={min_gap}s)"
    )
    return fixed


def render_srt(subtitles: List[Tuple[float, float, str]]) -> str:
    """Render subtitles list back to SRT format string."""
    if not subtitles:
        return ""

    lines = []
    for idx, (start, end, text) in enumerate(subtitles, start=1):
        start_ts = _seconds_to_srt_timestamp(start)
        end_ts = _seconds_to_srt_timestamp(end)
        lines.append(str(idx))
        lines.append(f"{start_ts} --> {end_ts}")
        lines.append(text.strip())
        lines.append("")
    return "\n".join(lines)


def optimize_srt_file(
    input_path: str,
    output_path: Optional[str] = None,
    min_duration: float = MIN_DURATION,
    min_gap: float = MIN_GAP,
    max_line_length: int = MAX_LINE_LENGTH,
) -> str:
    """Optimize an SRT file and save the result.

    If output_path is None, overwrites the input file.

    Returns: path to the optimized file (or empty string on failure).
    """
    if not input_path or not os.path.exists(input_path):
        logger.warning(f"Subtitle Optimizer: input not found: {input_path}")
        return ""

    try:
        with open(input_path, "r", encoding="utf-8-sig") as f:
            content = f.read()
    except Exception as e:
        logger.error(f"Subtitle Optimizer: failed to read {input_path}: {e}")
        return ""

    subs = parse_srt(content)
    if not subs:
        logger.warning(f"Subtitle Optimizer: no subtitles parsed from {input_path}")
        return ""

    optimized = optimize_subtitles(
        subs,
        min_duration=min_duration,
        min_gap=min_gap,
        max_line_length=max_line_length,
    )
    if not optimized:
        return ""

    srt_content = render_srt(optimized)

    if output_path is None:
        output_path = input_path

    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(srt_content)
        logger.success(f"Subtitle Optimizer: saved → {output_path}")
        return output_path
    except Exception as e:
        logger.error(f"Subtitle Optimizer: failed to write {output_path}: {e}")
        return ""


def is_available() -> bool:
    """Always available — pure Python, no external deps."""
    return True